# https://banzaicloud.com/docs/supertubes/kafka-operator/install-kafka-operator/
apiVersion: v1
kind: kbrew
app:
  repository:
    name: banzaicloud-stable
    url: https://kubernetes-charts.banzaicloud.com
    type: helm
  name: kafka-operator
  namespace: kafka
  sha256:
  version: 0.4.6
  pre_install:
  - apps:
    - cert-manager
    - zookeeper-operator
    - kube-prometheus-stack
  - steps: 
      # Create a Zookeeper cluster
      - |
        kubectl apply --namespace zookeeper -f - <<EOF
        apiVersion: zookeeper.pravega.io/v1beta1
        kind: ZookeeperCluster
        metadata:
            name: zookeeper
            namespace: zookeeper
        spec:
            replicas: 3
        EOF
      # Wait for Zookeeper cluster to be ready
      - |
        echo "Waiting for zookeeper cluster to be ready"
        retry=0
        while true;
        do
          replicas=$(kubectl get ZookeeperCluster -n zookeeper zookeeper -o jsonpath='{.status.replicas}')
          readyReplicas=$(kubectl get ZookeeperCluster -n zookeeper zookeeper -o jsonpath='{.status.readyReplicas}')
          if [ ! -z "${replicas}" ] && [ "${replicas}" = "${readyReplicas}" ]; then break; fi
          if [ "${retry}" = 20 ]; then echo "timed out while waiting for cluster to be ready"; exit 1; fi
          sleep 5
          retry=$((retry+1))
        done
  # Install the kafka-operator CustomResourceDefinition 
  - steps:
    - kubectl apply --validate=false -f https://github.com/banzaicloud/kafka-operator/releases/download/v0.14.0/kafka-operator.crds.yaml
  post_install:
  - steps:
    # Add your zookeeper service name to the configuration.
    - kubectl apply -n kafka -f https://raw.githubusercontent.com/banzaicloud/kafka-operator/master/config/samples/simplekafkacluster.yaml
    # Create the prometheus ServiceMonitors.
    - kubectl apply -n kafka -f https://raw.githubusercontent.com/banzaicloud/kafka-operator/master/config/samples/kafkacluster-prometheus.yaml
