before:
  hooks:
    - go mod download
builds:
- id: kbrew
  binary: kbrew
  main: cmd/cli/main.go
  ldflags: &ldflags
  - -s -w
    -X github.com/kbrew-dev/kbrew/pkg/version.Version={{.Tag}}
    -X github.com/kbrew-dev/kbrew/pkg/version.GitCommitID={{.Commit}}
    -X github.com/kbrew-dev/kbrew/pkg/version.BuildDate={{.Date}}
  env:
  - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - 386
    - amd64
    - arm
    - arm64
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
# temporary workaround to distribute binaries
release:
  github:
    owner: kbrew-dev
    name: kbrew-release
  draft: true
  prerelease: auto
  disable: false

