pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - base=main
      - "#approved-reviews-by>=1"
      - label!=hold-off-merging
      - label=ready-to-merge
      - status-success=build
    actions:
      merge:
        method: squash
        commit_message: title+body
        strict: smart
