name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
      GOPATH: /home/runner/work/kbrew
      GOBIN: /home/runner/work/kbrew/bin
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Install golint
      run: |
        go get -u golang.org/x/lint/golint
    - name: Before build
      run: |
        echo Workflow trigger - ${{ github.event_name }}
        ./hack/verify-gofmt.sh
        ./hack/verify-govet.sh
        ./hack/verify-golint.sh
        go mod verify
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
